# Consumer Choice Center 2026 brand tokens
PRIMARY_ORANGE = "#E95C1F"
PRIMARY_NAVY = "#22264E"

BASE_WHITE = "#FFFFFF"
WARM_WHITE = "#FFF7EF"
COOL_MIST = "#E7ECF4"
SLATE_BLUE = "#6F789B"

MARIGOLD = "#F4B544"
DEEP_TEAL = "#1E6F78"
BRIGHT_TEAL = "#00A6A6"
BRICK_CORAL = "#B9473A"
SAND_BEIGE = "#CDB79F"
SOFT_MINT = "#9BD8C7"

CHART_SEQUENCE = [
    PRIMARY_ORANGE,
    PRIMARY_NAVY,
    BRIGHT_TEAL,
    MARIGOLD,
    DEEP_TEAL,
    BRICK_CORAL,
    SLATE_BLUE,
    SOFT_MINT,
    SAND_BEIGE,
]
